projectType: sf-pm
projectTypeName: Client - Salesforce PM
modules:
  - core
  - projman
  - contracts
  - projplan
  - atlassian
  - learn
  - max-builder
createdAt: 2025-12-17T15:33:50.314Z
version: "1.0"
moduleVersions:
  core: 1.0.0
  projman: 1.0.0
  contracts: 1.0.0
  projplan: 1.0.0
  atlassian: 1.0.0
  learn: 1.2.0
  max-builder: 2.0.0
