projectType: pm-start
projectTypeName: Project Management - Start
modules:
  - core
  - pm-core
  - ppt-generator
createdAt: 2026-01-03T03:03:24.530Z
version: "1.0"
moduleVersions:
  core: 1.0.0
  pm-core: 1.0.0
  ppt-generator: 1.0.0
